const APP_VERSION='1.2';
(async()=>{try{const d=await fetch('version.json?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());if(d.version&&d.version!==APP_VERSION){const u=new URL(location.href);u.searchParams.set('v',d.version);location.replace(u)}}catch{}})();
(()=>{
const $=s=>document.querySelector(s),ui={cash:$('#cash'),pack:$('#packButton'),time:$('#timeButton'),main:$('#mainButton'),sell:$('#sellButton'),buy:$('#printerButton'),bar:$('#progressBar'),small:$('#statusSmall'),big:$('#statusBig'),toast:$('#toast'),flash:$('#flash'),selector:$('#selector'),title:$('#familyTitle'),sub:$('#familySub'),value:$('#familyValue'),pn:$('#printerName'),pd:$('#printerDesc'),pb:$('#printerBuild'),ps:$('#printerSpeed'),pp:$('#printerValueMult'),next:$('#printerNextHint')};
const toast=t=>{ui.toast.textContent=t;ui.toast.classList.add('show');setTimeout(()=>ui.toast.classList.remove('show'),1400)};
const PRINTERS=[
{name:'Starter Mini',price:0,speed:1,build:'Tiny',pack:'Tiny Collectibles',accent:0x4f7fff,desc:'Tiny open printer for miniature collectibles.'},
{name:'Creator One',price:1500,speed:1.15,build:'Small',pack:'Small Figures',accent:0x28c9d4,desc:'Larger bed for small figures like dogs, balls and giraffes.'},
{name:'Workshop Pro',price:9000,speed:1.32,build:'Medium',pack:'Medium Prints',accent:0x4fdc98,desc:'Stronger mechanics for medium display models.'},
{name:'Studio XL',price:45000,speed:1.52,build:'Large',pack:'Large Models',accent:0xff8d52,desc:'Large enclosed printer for premium decorative pieces.'},
{name:'Industrial Nova',price:180000,speed:1.78,build:'XL',pack:'XL Showpieces',accent:0xb56fff,desc:'Industrial-size machine for expensive showpiece prints.'}
];
const PACKS=[
{name:'Tiny',title:'Tiny Collectibles',families:['cats','dinos','ducks']},
{name:'Small',title:'Small Figures',families:['dogs','balls','giraffes']},
{name:'Medium',title:'Medium Prints',families:['robots','cars','sharks']},
{name:'Large',title:'Large Models',families:['dragons','rockets','sculptures']},
{name:'XL',title:'XL Showpieces',families:['mechs','supercars','spaceships']}
];
const F={
cats:{label:'Cats',sub:'5 cats • 3 common • 1 rare • 1 legendary',range:'$10–$50',w:[55,55,55,18,7],h:1.75,b:[1.3,1]},
dinos:{label:'Dinosaurs',sub:'7 species • 4 common • 2 rare • 1 legendary',range:'$12–$80',w:[38,38,38,38,16,16,6],h:1.9,b:[1.5,1]},
ducks:{label:'Ducks',sub:'Yellow duck • ultra-rare black Ugly Duckling',range:'$8–$250',w:[98.6,1.4],h:1.65,b:[1.5,.9]},
dogs:{label:'Dogs',sub:'5 small dog figures',range:'$60–$300',w:[52,52,52,18,6],h:2,b:[1.7,1.1]},balls:{label:'Balls',sub:'Sports and novelty balls',range:'$50–$280',w:[52,52,52,18,6],h:1.55,b:[1.5,1.5]},giraffes:{label:'Giraffes',sub:'5 taller giraffe figures',range:'$75–$340',w:[52,52,52,18,6],h:2.5,b:[1.35,1.05]},
robots:{label:'Robots',sub:'Medium collectible robots',range:'$220–$950',w:[50,50,50,18,6],h:2.5,b:[1.7,1.2]},cars:{label:'Cars',sub:'Medium display cars',range:'$250–$1,100',w:[50,50,50,18,6],h:1.35,b:[2,1.1]},sharks:{label:'Sharks',sub:'Different shark silhouettes',range:'$230–$1,000',w:[50,50,50,18,6],h:1.4,b:[2,1.1]},
dragons:{label:'Dragons',sub:'Large fantasy dragons',range:'$900–$4,500',w:[48,48,48,18,5],h:2.65,b:[2.2,1.4]},rockets:{label:'Rockets',sub:'Large rockets and launch models',range:'$850–$4,200',w:[48,48,48,18,5],h:2.9,b:[1.5,1.5]},sculptures:{label:'Sculptures',sub:'Large decorative sculptures',range:'$1,000–$5,000',w:[48,48,48,18,5],h:2.6,b:[1.8,1.35]},
mechs:{label:'Mechs',sub:'XL mechanical showpieces',range:'$6,500–$35,000',w:[46,46,46,18,4],h:3,b:[2.4,1.6]},supercars:{label:'Supercars',sub:'XL automotive display models',range:'$7,000–$38,000',w:[46,46,46,18,4],h:1.5,b:[2.65,1.45]},spaceships:{label:'Spaceships',sub:'XL sci-fi ships',range:'$7,500–$42,000',w:[46,46,46,18,4],h:1.8,b:[2.7,1.75]}}
const std=(p,n,v,c)=>n.map((name,i)=>({id:p+i,name,rar:i<3?'Common':i===3?'Rare':'Legendary',value:i<3?v[0]:i===3?v[1]:v[2],color:c[i%c.length],kind:p}));
const V={
cats:std('cat',['Sleepy Cat','Curly Tail Cat','Chubby Cat','Royal Cat','Galaxy Cat'],[10,25,50],[0xf0d7b6,0xd7d9df,0xd79f6e,0x8fd0ff,0xffb463]),
dinos:[{id:'trex',name:'Tiny T-Rex',rar:'Common',value:12,color:0x79cc79,kind:'dino'},{id:'stego',name:'Stegosaurus',rar:'Common',value:12,color:0x9cd26d,kind:'dino'},{id:'bronto',name:'Brachiosaurus',rar:'Common',value:12,color:0x84cdb8,kind:'dino'},{id:'raptor',name:'Velociraptor',rar:'Common',value:12,color:0x6fc0d2,kind:'dino'},{id:'tri',name:'Triceratops',rar:'Rare',value:30,color:0xbacb58,kind:'dino'},{id:'anky',name:'Ankylosaurus',rar:'Rare',value:30,color:0xcabd75,kind:'dino'},{id:'crystal',name:'Crystal Rex',rar:'Legendary',value:80,color:0xe38cff,kind:'dino'}],
ducks:[{id:'yellow',name:'Yellow Duck',rar:'Common',value:8,color:0xf5cc43,kind:'duck'},{id:'ugly',name:'Ugly Duckling',rar:'Legendary',value:250,color:0x252a31,kind:'duck'}],
dogs:std('dog',['Puppy','Corgi','Beagle','Husky','Royal Hound'],[60,140,300],[0xd8b18b,0xe6c59d,0x9b765f,0x9ec8ea,0xffcf63]),balls:std('ball',['Soccer Ball','Basketball','Baseball','Disco Ball','Cosmic Ball'],[50,130,280],[0xe9edf2,0xe17c39,0xf3eee5,0xbce9ff,0xc273ff]),giraffes:std('giraffe',['Young Giraffe','Curious Giraffe','Tall Giraffe','Safari Giraffe','Golden Giraffe'],[75,170,340],[0xe5b85a,0xdba84e,0xf0c96c,0xb9d477,0xffd45c]),
robots:std('robot',['Service Bot','Box Bot','Worker Bot','Sentinel Bot','Quantum Bot'],[220,500,950],[0x7da9d9,0x85c8c5,0x9aa8ba,0xe6815b,0xc07cff]),cars:std('car',['City Car','Rally Car','Coupe','Track Car','Hypercar'],[250,600,1100],[0x5da1ff,0xef5757,0xf0c34b,0x77d68f,0xb66cff]),sharks:std('shark',['Reef Shark','Mako Shark','Hammerhead','Great White','Ghost Shark'],[230,550,1000],[0x6fa7bd,0x6398b3,0x789ab1,0xbfc8cf,0xc48cff]),
dragons:std('dragon',['Young Dragon','Stone Dragon','Forest Dragon','Fire Dragon','Celestial Dragon'],[900,2200,4500],[0x74c779,0x9c9ca5,0x55b785,0xee7655,0xa974ff]),rockets:std('rocket',['Explorer Rocket','Cargo Rocket','Lunar Rocket','Nova Rocket','Starfire Rocket'],[850,2100,4200],[0xe8edf5,0xc9d0db,0xb5d8ff,0xff9f5c,0xa878ff]),sculptures:std('sculpt',['Abstract Bust','Twist Sculpture','Wave Sculpture','Gallery Piece','Masterpiece'],[1000,2500,5000],[0xe7e0d4,0xc9d0d8,0xdac0a8,0x82c8c0,0xffcf73]),
mechs:std('mech',['Utility Mech','Defense Mech','Loader Mech','Titan Mech','Apex Mech'],[6500,15000,35000],[0x738aa8,0x59758f,0x8a9b73,0xe06a53,0xb36cff]),supercars:std('supercar',['GT Coupe','Roadster','Track Special','Prototype R','Nebula One'],[7000,17000,38000],[0x4d8dff,0xf25959,0xe8bd4f,0x54d19a,0xb96cff]),spaceships:std('ship',['Scout Ship','Cargo Ship','Interceptor','Battlecruiser','Flagship'],[7500,19000,42000],[0x93aabd,0x788a99,0x65b5d0,0xe77d5b,0xb779ff])};
const KEY='printer-prototype-v12';try{localStorage.removeItem('printer-prototype');localStorage.removeItem('printer-prototype-v11')}catch{}
let s={cash:0,printer:0,family:'cats'},raw={};try{raw=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};s.cash=+raw.cash||0;s.printer=Math.max(0,Math.min(4,+raw.printer||0));s.family=raw.family||PACKS[s.printer].families[0];let pack=Math.min(s.printer,F[s.family]?.tier??s.printer);if(!PACKS[pack].families.includes(s.family))s.family=PACKS[pack].families[0];const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
let time=1,state='idle',variant=null,mesh=null,elapsed=0,prog=0,doneAt=0;
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x0d1220,8,18);const camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.1,50);camera.position.set(6,4.1,7.9);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.localClippingEnabled=true;$('#scene').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xdde8ff,0x17120e,1.4));const key=new THREE.DirectionalLight(0xffffff,2.1);key.position.set(5,7,5);key.castShadow=true;scene.add(key);const floor=new THREE.Mesh(new THREE.CircleGeometry(8,48),new THREE.MeshStandardMaterial({color:0x111a29,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const printer=new THREE.Group();scene.add(printer);const dark=new THREE.MeshStandardMaterial({color:0x101620,metalness:.6,roughness:.35}),body=new THREE.MeshStandardMaterial({color:0x263143,metalness:.25,roughness:.45}),accent=new THREE.MeshStandardMaterial({color:0x4f7fff,emissive:0x173c88,emissiveIntensity:.4,metalness:.3,roughness:.3});const box=(g,w,h,d,m,x,y,z)=>{const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;g.add(q);return q};box(printer,4.6,.35,4,dark,0,.25,0);box(printer,4,.18,3.4,body,0,.48,0);[-1.8,1.8].forEach(x=>[-1.45,1.45].forEach(z=>box(printer,.18,3.4,.18,dark,x,2,z)));box(printer,3.8,.18,.18,dark,0,3.65,-1.45);box(printer,3.8,.18,.18,dark,0,3.65,1.45);const bed=box(printer,3,.14,2.7,dark,0,.62,0);box(printer,2.8,.05,2.45,new THREE.MeshStandardMaterial({color:0x172233,metalness:.2,roughness:.3}),0,.73,0);const gantry=new THREE.Group();printer.add(gantry);box(gantry,3.4,.18,.22,dark,0,0,-.15);const head=new THREE.Group();printer.add(head);box(head,.72,.52,.6,accent,0,0,0);const nozzle=new THREE.Mesh(new THREE.ConeGeometry(.08,.3,16),new THREE.MeshStandardMaterial({color:0xe4a15f,metalness:.8,roughness:.15}));nozzle.rotation.x=Math.PI;nozzle.position.set(0,-.34,.1);head.add(nozzle);const glow=new THREE.PointLight(0xffb15c,0,1.5,2);glow.position.set(0,-.42,.1);head.add(glow);const glass=new THREE.MeshStandardMaterial({color:0x9fd8ff,transparent:true,opacity:.16,roughness:.05});const enclosure=[box(printer,.04,2.8,2.7,glass,-1.65,2.15,0),box(printer,.04,2.8,2.7,glass,1.65,2.15,0),box(printer,3.3,2.8,.04,glass,0,2.15,1.32)];
const base=.78,clip=new THREE.Plane(new THREE.Vector3(0,-1,0),base),mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.34,metalness:.04,clippingPlanes:[clip]}),add=(g,geo,m,x,y,z,sx=1,sy=1,sz=1,rx=0,ry=0,rz=0)=>{const q=new THREE.Mesh(geo,m);q.position.set(x,y,z);q.scale.set(sx,sy,sz);q.rotation.set(rx,ry,rz);q.castShadow=true;g.add(q);return q};
function build(v,f){const g=new THREE.Group(),c=mat(v.color),d=mat(0x151b24),a=mat(0xf4d169);if(f==='cats'||f==='dogs'){add(g,new THREE.SphereGeometry(.62,20,16),c,0,.7,0,1.1,.8,.9);add(g,new THREE.SphereGeometry(.42,18,14),c,.48,1.2,0);add(g,new THREE.ConeGeometry(.16,.36,3),c,.34,1.55,.2);add(g,new THREE.ConeGeometry(.16,.36,3),c,.34,1.55,-.2);[-.25,.18].forEach(x=>[.16,-.16].forEach(z=>add(g,new THREE.CylinderGeometry(.07,.08,.55,10),c,x,.25,z)));if(f==='dogs')add(g,new THREE.CylinderGeometry(.05,.08,.7,10),c,-.65,.82,0,0,0,-.8);}
else if(f==='ducks'){add(g,new THREE.SphereGeometry(.72,24,18),c,0,.58,0,1.15,.85,1);add(g,new THREE.SphereGeometry(.45,22,16),c,.42,1.22,0);add(g,new THREE.ConeGeometry(.18,.45,4),mat(0xf08a31),.84,1.18,0,1,.6,1,0,0,-Math.PI/2);}
else if(f==='dinos'||f==='dragons'||f==='sharks'){add(g,new THREE.SphereGeometry(.65,20,14),c,0,.78,0,1.45,.62,.72);add(g,new THREE.SphereGeometry(.3,16,12),c,.72,1.12,0);add(g,new THREE.CylinderGeometry(.05,.1,1.0,10),c,-.82,.85,0,0,0,-1);if(f==='dragons'){add(g,new THREE.BoxGeometry(.08,.75,.55),a,-.05,1.3,.5,1,1,1,0,0,.75);add(g,new THREE.BoxGeometry(.08,.75,.55),a,-.05,1.3,-.5,1,1,1,0,0,-.75);}if(f==='sharks'){add(g,new THREE.ConeGeometry(.25,.7,3),c,0,1.35,0);}}
else if(f==='balls'){add(g,new THREE.SphereGeometry(.72,28,22),c,0,.72,0);if(v.rar!=='Common')for(let i=0;i<8;i++)add(g,new THREE.SphereGeometry(.05,8,6),a,Math.cos(i*.785)*.63,.72+Math.sin(i*.785)*.5,0);}
else if(f==='giraffes'){add(g,new THREE.SphereGeometry(.5,20,14),c,0,.68,0,1.15,.75,.82);add(g,new THREE.CylinderGeometry(.13,.17,1.35,12),c,.35,1.55,0,0,0,-.08);add(g,new THREE.SphereGeometry(.28,16,12),c,.37,2.23,0);[-.25,.1].forEach(x=>[.14,-.14].forEach(z=>add(g,new THREE.CylinderGeometry(.06,.07,.82,10),c,x,.25,z)));}
else if(f==='robots'||f==='mechs'){const k=f==='mechs'?1.18:1;add(g,new THREE.BoxGeometry(1.05*k,.9*k,.72*k),c,0,.9*k,0);add(g,new THREE.BoxGeometry(.82*k,.58*k,.62*k),c,0,1.65*k,0);add(g,new THREE.BoxGeometry(.2*k,.75*k,.25*k),d,-.72*k,.9*k,0);add(g,new THREE.BoxGeometry(.2*k,.75*k,.25*k),d,.72*k,.9*k,0);add(g,new THREE.BoxGeometry(.25*k,.62*k,.3*k),d,-.28*k,.3*k,0);add(g,new THREE.BoxGeometry(.25*k,.62*k,.3*k),d,.28*k,.3*k,0);}
else if(f==='cars'||f==='supercars'){const k=f==='supercars'?1.18:1;add(g,new THREE.BoxGeometry(1.9*k,.45,.9*k),c,0,.55,0);add(g,new THREE.BoxGeometry(1.05*k,.35,.68*k),c,.05,.85,0);[-.7*k,.7*k].forEach(x=>[-.43*k,.43*k].forEach(z=>add(g,new THREE.CylinderGeometry(.18,.18,.12,14),d,x,.34,z,1,1,1,Math.PI/2)));}
else if(f==='rockets'){add(g,new THREE.CylinderGeometry(.42,.48,1.7,20),c,0,1.25,0);add(g,new THREE.ConeGeometry(.42,.75,20),a,0,2.47,0);for(let i=0;i<3;i++){const q=i*Math.PI*2/3;add(g,new THREE.BoxGeometry(.12,.65,.48),d,Math.cos(q)*.42,.48,Math.sin(q)*.42,1,1,1,0,-q);}}
else if(f==='sculptures'){add(g,new THREE.CylinderGeometry(.58,.72,.28,24),d,0,.18,0);add(g,new THREE.SphereGeometry(.62,22,16),c,0,.9,0,.85,1.15,.8);add(g,new THREE.TorusKnotGeometry(.38,.1,64,9,2,3),a,0,1.65,0);}
else if(f==='spaceships'){add(g,new THREE.SphereGeometry(.68,22,14),c,0,.75,0,1.55,.38,.9);add(g,new THREE.BoxGeometry(1.9,.12,.5),c,-.15,.78,0);add(g,new THREE.BoxGeometry(.8,.16,1.55),c,-.1,.75,0);add(g,new THREE.ConeGeometry(.22,.72,4),a,.95,.75,0,1,1,1,0,0,-Math.PI/2);}
g.position.set(0,base,0);scene.add(g);return g}
const layer=new THREE.Mesh(new THREE.PlaneGeometry(2,1.5),new THREE.MeshBasicMaterial({color:0xffdf9a,transparent:true,opacity:.3,side:THREE.DoubleSide}));layer.rotation.x=-Math.PI/2;layer.visible=false;scene.add(layer);
const currentP=()=>PRINTERS[s.printer],currentPack=()=>PACKS[pack],roll=f=>{const w=F[f].w,a=V[f],sum=w.reduce((x,y)=>x+y,0);let r=Math.random()*sum;for(let i=0;i<a.length;i++){r-=w[i];if(r<=0)return a[i]}return a.at(-1)},dur=()=>[4300,6500,8200,10300,12600][pack]/currentP().speed;
function render(){ui.selector.innerHTML='';currentPack().families.forEach(f=>{const b=document.createElement('button');b.className='family-btn'+(f===s.family?' active':'');b.innerHTML=F[f].label.toUpperCase()+'<small>'+F[f].range+'</small>';b.onclick=()=>{if(state==='printing')return;s.family=f;variant=null;if(mesh)mesh.visible=false;save();render()};ui.selector.appendChild(b)});ui.pack.textContent=`PACK ${pack+1}/${s.printer+1} • ${currentPack().name.toUpperCase()}`;ui.cash.textContent='$'+s.cash.toLocaleString();ui.title.textContent=variant?variant.name:F[s.family].label+' Mystery Print';ui.sub.textContent=variant?variant.rar+' • '+currentPack().title:F[s.family].sub;ui.value.textContent=variant?'$'+variant.value.toLocaleString():F[s.family].range;const p=currentP();ui.pn.textContent=p.name;ui.pd.textContent=p.desc;ui.pb.textContent=p.build;ui.ps.textContent=p.speed.toFixed(2)+'×';ui.pp.textContent=p.pack;const n=PRINTERS[s.printer+1];ui.next.textContent=n?n.name:'MAXED';ui.buy.innerHTML=n?`NEXT PRINTER<br><span>$${n.price.toLocaleString()}</span>`:'ALL PRINTERS<br><span>MAXED</span>';ui.buy.disabled=!n||state==='printing'||s.cash<n.price;ui.buy.classList.toggle('ready',!!n&&s.cash>=n.price&&state!=='printing');if(state==='idle'){ui.main.disabled=false;ui.sell.disabled=true;ui.main.textContent='PRINT';ui.sell.textContent='SELL';ui.small.textContent='READY TO PRINT';ui.big.textContent=currentPack().title}else if(state==='printing'){ui.main.disabled=true;ui.sell.disabled=true;ui.main.textContent='PRINTING…'}else{ui.main.disabled=true;ui.sell.disabled=false;ui.sell.textContent='SELL +$'+variant.value.toLocaleString();ui.small.textContent=variant.rar.toUpperCase();ui.big.textContent=variant.name}}
function printerLook(){const p=currentP();accent.color.setHex(p.accent);accent.emissive.setHex(p.accent);enclosure.forEach(x=>x.visible=s.printer>0);printer.scale.setScalar(1+s.printer*.035)}
ui.main.onclick=()=>{if(state!=='idle')return;variant=roll(s.family);if(mesh){scene.remove(mesh);mesh.geometry?.dispose?.()}mesh=build(variant,s.family);clip.constant=base;elapsed=prog=0;state='printing';layer.visible=true;glow.intensity=3.5;render()};ui.sell.onclick=()=>{if(state!=='complete')return;s.cash+=variant.value;save();state='idle';toast('+$'+variant.value.toLocaleString()+' SOLD');render()};ui.buy.onclick=()=>{const n=PRINTERS[s.printer+1];if(!n||s.cash<n.price||state==='printing')return;s.cash-=n.price;s.printer++;pack=s.printer;s.family=PACKS[pack].families[0];variant=null;if(mesh)mesh.visible=false;save();printerLook();toast('NEW PACK • '+PACKS[pack].title);render()};ui.pack.onclick=()=>{if(state==='printing')return;pack=(pack+1)%(s.printer+1);s.family=PACKS[pack].families[0];variant=null;if(mesh)mesh.visible=false;save();render()};ui.time.onclick=()=>{const a=[1,.5,.25,.1],i=a.indexOf(time);time=a[(i+1)%a.length];ui.time.textContent='TIME '+time+'×'};
let prev=performance.now();function anim(now){requestAnimationFrame(anim);const dt=Math.min(.05,(now-prev)/1000);prev=now;if(state==='printing'){elapsed+=dt*1000*time;prog=Math.min(1,elapsed/dur());const f=F[s.family],rows=7,t=prog*rows,row=Math.min(rows-1,Math.floor(t)),u=t-row,z=-f.b[1]/2+f.b[1]*(row/(rows-1)),x=(row%2?1-u:u)*f.b[0]-f.b[0]/2,y=base+f.h*prog;clip.constant=y;head.position.set(x,y+.58,z);gantry.position.y=y+.74;layer.position.set(0,y+.005,0);layer.scale.set(f.b[0]/1.6,f.b[1]/1.1,1);ui.bar.style.width=Math.round(prog*100)+'%';ui.small.textContent=prog<.15?'FIRST LAYER':prog>.9?'FINAL LAYERS':'PRINTING LAYERS';ui.big.textContent=Math.round(prog*100)+'%';glow.intensity=2.2+.6*Math.sin(now*.03);if(prog>=1){state='complete';doneAt=now;clip.constant=base+4;layer.visible=false;glow.intensity=0;ui.flash.classList.add('on');setTimeout(()=>ui.flash.classList.remove('on'),220);toast(variant.rar.toUpperCase()+' • '+variant.name);render()}}else{gantry.position.y+=(2.48-gantry.position.y)*Math.min(1,dt*3);head.position.x+=(1.15-head.position.x)*Math.min(1,dt*3.5);head.position.y+=(2.95-head.position.y)*Math.min(1,dt*3.5);head.position.z+=(.8-head.position.z)*Math.min(1,dt*3.5);ui.bar.style.width=state==='complete'?'100%':'0%';if(mesh)mesh.rotation.y=state==='complete'?Math.sin((now-doneAt)*.001)*.18:mesh.rotation.y*.9}camera.lookAt(0,1.3,0);renderer.render(scene,camera)}
printerLook();render();toast('Progress reset • 5 printer tiers live');requestAnimationFrame(anim);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
})();
