function weights(f){return W[f]||[50,50,50,18,6]}
function roll(f){const arr=V[f],w=weights(f),sum=w.reduce((a,b)=>a+b,0);let r=Math.random()*sum;for(let i=0;i<arr.length;i++){r-=w[i];if(r<=0)return arr[i]}return arr[arr.length-1]}
function duration(){return (s.pack+1)*500+5200/PRINTERS[s.printer].speed}
function uiUpdate(){ui.cash.textContent='$'+Math.round(s.cash);ui.pack.textContent=`PACK ${s.pack+1}/${s.printer+1}`;const ff=F[s.family];ui.title.textContent=variant?variant.name:ff.label;ui.sub.textContent=variant?(state==='reveal'?`${variant.rar} • auto-selling...`:`${variant.rar} collectible`):ff.sub;ui.value.textContent=variant?`$${variant.value}`:ff.range;ui.selector.innerHTML='';PACKS[s.pack].forEach(f=>{const b=document.createElement('button');b.className='family-btn'+(f===s.family?' active':'');b.innerHTML=`${F[f].label.toUpperCase()}<small>${F[f].range}</small>`;b.onclick=()=>{if(state!=='idle')return;s.family=f;variant=null;if(active)active.visible=false;save();uiUpdate()};ui.selector.appendChild(b)});ui.main.disabled=state!=='idle';ui.main.textContent=state==='printing'?'PRINTING…':state==='reveal'?'SOLD SOON…':'PRINT';const next=PRINTERS[s.printer+1];ui.buy.disabled=!next||state!=='idle'||s.cash<next?.price;ui.buy.classList.toggle('ready',!!next&&s.cash>=next.price);ui.buy.innerHTML=next?`NEXT PRINTER<br><span>$${next.price}</span>`:'MAX PRINTER';ui.big.textContent=state==='printing'?Math.round(prog*100)+'%':state==='reveal'?variant.name:PRINTERS[s.printer].name;ui.small.textContent=state==='printing'?'PRINTING LAYERS':state==='reveal'?`${variant.rar.toUpperCase()} • $${variant.value}`:'READY TO PRINT';document.body.classList.toggle('printing',state==='printing');document.body.classList.toggle('revealing',state==='reveal')}
function buy(){const n=PRINTERS[s.printer+1];if(!n||s.cash<n.price||state!=='idle')return;s.cash-=n.price;s.printer++;s.pack=s.printer;s.family=PACKS[s.pack][0];accent.color.setHex(n.accent);accent.emissive.setHex(n.accent);save();toast('NEW PRINTER • '+n.name);uiUpdate()}
function start(){if(state!=='idle')return;variant=roll(s.family);if(active)active.visible=false;active=getModel(variant,s.family);active.visible=true;active.rotation.set(0,0,0);clip.constant=baseY;elapsed=0;prog=0;state='printing';autoSold=false;nozzleGlow.intensity=4.5;revealLight.intensity=0;uiUpdate()}
function complete(){state='reveal';clip.constant=baseY+5;nozzleGlow.intensity=0;revealStart=performance.now();autoSold=false;ui.flash.classList.add('on');setTimeout(()=>ui.flash.classList.remove('on'),180);toast(`${variant.rar.toUpperCase()} • ${variant.name} • $${variant.value}`);orbit.target.set(0,1.45,0);orbit.dist=7;applyCamera();revealLight.color.setHex(variant.rar==='Legendary'?0xffc36d:variant.rar==='Rare'?0x79cfff:0xffffff);revealLight.intensity=variant.rar==='Legendary'?3.2:variant.rar==='Rare'?2.2:1.5;uiUpdate()}
function autoSell(){if(state!=='reveal'||autoSold)return;autoSold=true;s.cash+=variant.value;save();toast(`SOLD +$${variant.value}`);state='idle';revealLight.intensity=0;uiUpdate()}
ui.main.onclick=start;ui.buy.onclick=buy;ui.pack.onclick=()=>{if(state!=='idle'||s.printer===0)return;s.pack=(s.pack+1)%(s.printer+1);s.family=PACKS[s.pack][0];variant=null;if(active)active.visible=false;save();uiUpdate()};ui.time.onclick=()=>{const arr=[1,.5,.25,.1],i=arr.indexOf(timeScale);timeScale=arr[(i+1)%arr.length];ui.time.textContent='TIME '+timeScale+'×'};
const orbit={yaw:.67,pitch:.37,dist:9,target:new THREE.Vector3(0,1.35,0),drag:false,x:0,y:0};
function applyCamera(){orbit.pitch=Math.max(.08,Math.min(1.25,orbit.pitch));orbit.dist=Math.max(4.5,Math.min(12,orbit.dist));const cp=Math.cos(orbit.pitch);camera.position.set(orbit.target.x+Math.sin(orbit.yaw)*cp*orbit.dist,orbit.target.y+Math.sin(orbit.pitch)*orbit.dist,orbit.target.z+Math.cos(orbit.yaw)*cp*orbit.dist);camera.lookAt(orbit.target)}
function resetView(){orbit.yaw=.67;orbit.pitch=.37;orbit.dist=state==='reveal'?7:9;orbit.target.set(0,state==='reveal'?1.45:1.35,0);applyCamera()}ui.view.onclick=resetView;
const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{orbit.drag=true;orbit.x=e.clientX;orbit.y=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!orbit.drag)return;const dx=e.clientX-orbit.x,dy=e.clientY-orbit.y;orbit.x=e.clientX;orbit.y=e.clientY;orbit.yaw-=dx*.006;orbit.pitch+=dy*.004;applyCamera()});canvas.addEventListener('pointerup',e=>{orbit.drag=false;try{canvas.releasePointerCapture(e.pointerId)}catch{}});canvas.addEventListener('wheel',e=>{e.preventDefault();orbit.dist+=e.deltaY*.008;applyCamera()},{passive:false});let pinch=null;canvas.addEventListener('touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinch){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);orbit.dist*=pinch/d;pinch=d;applyCamera()}},{passive:true});
uiUpdate();resetView();toast('Prototype 2.1 • sculpted figurines');
let prev=performance.now();
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-prev)/1000);prev=now;if(state==='printing'&&active){elapsed+=dt*1000*timeScale;prog=Math.min(1,elapsed/duration());const ff=F[s.family],p=prog<.08?0:Math.min(1,(prog-.08)/.92),height=baseY+ff.h*p;clip.constant=height;const rows=10,phase=(prog*rows)%1,row=Math.floor(prog*rows),x=(row%2?1:-1)*(ff.b[0]*.48)*(phase*2-1),z=-ff.b[1]*.34+(row%4)*(ff.b[1]*.22);head.position.set(x,height+.57,z);gantry.position.y=height+.74;bedGroup.position.z=Math.sin(now*.004)*.022;ui.bar.style.width=Math.round(prog*100)+'%';ui.big.textContent=Math.round(prog*100)+'%';nozzleGlow.intensity=2.5+.85*Math.sin(now*.025);if(prog>=1)complete()}else{ui.bar.style.width=state==='reveal'?'100%':'0%';head.position.x+=(1.15-head.position.x)*Math.min(1,dt*3);head.position.y+=(2.9-head.position.y)*Math.min(1,dt*3);head.position.z+=(.78-head.position.z)*Math.min(1,dt*3);gantry.position.y+=(2.45-gantry.position.y)*Math.min(1,dt*3);bedGroup.position.z*=.9;if(active&&state==='reveal'){active.rotation.y+=dt*.32;active.position.y=baseY+Math.sin(now*.003)*.025;if(now-revealStart>3200)autoSell()}else if(active){active.position.y+=(baseY-active.position.y)*Math.min(1,dt*5)}}renderer.render(scene,camera)}
requestAnimationFrame(animate);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));applyCamera()});
